apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-redis
spec:
  selector:
    matchLabels:
      app: patiwat-redis
  template:
    metadata:
      labels:
        app: patiwat-redis
    spec:
      containers:
        - name: patiwat-redis
          image: redis:7-alpine
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: REDIS_PORT
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: REDIS_HOST
          volumeMounts:
            - name: patiwat-redis-data-storage
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: patiwat-redis-data-storage
          persistentVolumeClaim:
            claimName: patiwat-redis-storage
