apiVersion: apps/v1
kind: Deployment
metadata:
  name: patiwat-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patiwat-postgres
  template:
    metadata:
      labels:
        app: patiwat-postgres
    spec:
      containers:
        - name: patiwat-postgres
          image: quay.io/fedora/postgresql-16:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: patiwat-guestbook-secrets
                  key: DB_NAME
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: patiwat-postgres-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: patiwat-postgres-storage
          persistentVolumeClaim:
            claimName: patiwat-postgres-storge
